import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import '@/styles/globals.css';
import Header from '@/components/header';
import { cn } from '@/lib/utils';
import { fontInter, fontStixTwo } from '@/lib/fonts';
import QueryProvider from '@/providers/query-client';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang="en"
      className={cn(
        'bg-white text-slate-900 antialiased light',
        fontInter.variable,
        fontStixTwo.variable
      )}
    >
      <body className="min-h-screen font-inter font-medium bg-slate-50 antialiased">
        <div className="min-h-screen max-w-5xl mx-auto">
          <QueryProvider>
            <Header />
            {children}
            <Toaster position="top-right" richColors duration={5000} />
          </QueryProvider>
        </div>
      </body>
    </html>
  );
}
